//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminDetail
    {
        public long Id { get; set; }
        public string AdminName { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Last_LoggedIn_Time { get; set; }
        public Nullable<System.DateTime> Last_LoggedOut_Time { get; set; }
    }
}
